FunctionProject/FunctionProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

FunctionProject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('', views.home, name='home'),
  path('regist/', views.regist, name='regist'),
  path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
  path('user_login/', views.user_login, name='user_login'),
  path('user_logout/', views.user_logout, name='user_logout'),
  path('user_edit/', views.user_edit, name='user_edit'),
  path('change_password/', views.change_password, name='change_password'),
]

FunctionProject/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
  path('create_theme', views.create_theme, name='create_theme'),
  path('list_themes', views.list_themes, name='list_themes'),
  path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
  path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
]

FunctionProject/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navv¥bar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
    {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'boards:list_themes' %}">掲示板一覧</a>
      <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
      <a class="navbar-brand" href="{% url 'accounts:user_edit' %}">ユーザ情報更新</a>
    {% else %}
      <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
      <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザ登録</a>
    {% endif %}
  </nav>
  {% block content %}
  {% endblock %}
</body>
</html>