FunctionProject/FunctionProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

FunctionProject/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
  path('create_theme', views.create_theme, name='create_theme'),
  path('list_themes', views.list_themes, name='list_themes'),
  path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
  path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
]

FunctionProject/boards/models.py
from django.db import models

# Create your models here.

class ThemesManager(models.Manager):

  def fetch_all_themes(self):
    return self.order_by('id').all()

class Themes(models.Model):
  title = models.CharField(max_length=255)
  user = models.ForeignKey(
    'accounts.Users', on_delete=models.CASCADE
  )

  objects = ThemesManager()

  class Meta:
    db_table = 'themes'

class Comments(models.Model):
  comment = models.CharField(max_length= 1000)
  user = models.ForeignKey(
    'accounts.Users', on_delete=models.CASCADE
  )
  theme = models.ForeignKey(
    'Themes', on_delete=models.CASCADE
  )

  class Meta:
    db_table = 'comments'

FunctionProject/boards/forms.py
from django import forms
from .models import Themes, Comments

class CreateThemeForm(forms.ModelForm):
  title = forms.CharField(label='タイトル')

  class Meta:
    model = Themes
    fields = ('title',)


class DeleteThemeForm(forms.ModelForm):
  
  class Meta:
    model = Themes
    fields = []

FunctionProject/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Themes
from django.http import Http404

# Create your views here.
def create_theme(request):
  create_theme_form = forms.CreateThemeForm(request.POST or None)
  if create_theme_form.is_valid():
    # ここでユーザーをセットする
    create_theme_form.instance.user = request.user
    create_theme_form.save()
    messages.success(request, '掲示板を作成しました。')
    return redirect('boards:list_themes')

  return render(request, 'boards/create_theme.html', context={
    'create_theme_form': create_theme_form
  })

def list_themes(request):
  themes = Themes.objects.fetch_all_themes()
  return render(request, 'boards/list_themes.html', context={
    'themes': themes
  })

def edit_theme(request, id):
  theme = get_object_or_404(Themes, id=id)
  if theme.user_id != request.user.id:
    raise Http404
  
  edit_theme_form = forms.CreateThemeForm(request.POST or None, instance=theme)
  if edit_theme_form.is_valid():
    edit_theme_form.save()
    messages.success(request, '掲示板を更新しました。')
    return redirect('boards:list_themes')
  
  return render(request, 'boards/edit_theme.html', context={
    'edit_theme_form': edit_theme_form,
    'id': id,
  })

def delete_theme(request, id):
  theme = get_object_or_404(Themes, id=id)
  if theme.user_id != request.user.id:
    raise Http404
  
  delete_theme_form = forms.DeleteThemeForm(request.POST or None, instance=theme)
  if delete_theme_form.is_valid():  # csrf_tokenのチェック
    theme.delete()
    messages.success(request, '掲示板を削除しました。')
    return redirect('boards:list_themes')

  return render(request, 'boards/delete_theme.html', context={
    'delete_theme_form': delete_theme_form,
    'id': id,
  })

FunctionProject/templates/boards/create_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板作成画面</h3>
<form method="POST">
    {% csrf_token %}
    {{ create_theme_form.as_p }}
    <input type="submit" value="掲示板作成">
</form>
{% endblock %}

FunctionProject/templates/boards/delete_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板削除画面</h3>
<form method="POST">
    {% csrf_token %}
    {{ delete_theme_form.as_p }}
    <input type="submit" value="削除する">
</form>
{% endblock %}

FunctionProject/templates/boards/edit_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板編集画面</h3>
<form method="POST">
    {% csrf_token %}
    {{ edit_theme_form.as_p }}
    <input type="submit" value="掲示板更新">
</form>
<p><a href="{% url 'boards:delete_theme' id=id %}">削除する</a></p>
{% endblock %}

FunctionProject/templates/boards/list_themes.html
{% extends "base.html" %}
{% block content %}

{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}

<h3>掲示板一覧画面</h3>
<p><a class="navbar-brand" href="{% url 'boards:create_theme' %}">掲示板作成</a></p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>タイトル</th>
            <th>作成者</th>
        </tr>
    </thead>
    <tbody>
        {% for theme in themes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ theme.title }}</td>
                {% if theme.user.id == user.id %}
                    <td><a href="{% url 'boards:edit_theme' id=theme.id %}">{{ theme.user }}</a></td>
                {% else %}
                    <td>{{ theme.user }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}